### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by NuonuoLabs** [xudjx/djkeyboard#2]
小数点怎么设置能用？我默认加 只能加数字。。。

**Comment by xudjx** [comment]
抱歉这么久才看到。
EditText本身还受到InputType的控制，所以即便在NumberKeyboard中通过Editable.insert()写入了小数点，如果inputType不支持小数点输入，也是会被过滤掉的。
如果要支持小数点，inputType增加InputType.TYPE_NUMBER_FLAG_DECIMAL， 同时numberKeyboard.setEnableDotInput(true);

**Comment by xudjx** [comment]
> 小数点怎么设置能用？我默认加 只能加数字。。。

抱歉这么久才看到。
EditText本身还受到InputType的控制，所以即便在NumberKeyboard中通过Editable.insert()写入了小数点，如果inputType不支持小数点输入，也是会被过滤掉的。
如果要支持小数点，inputType增加InputType.TYPE_NUMBER_FLAG_DECIMAL， 同时numberKeyboard.setEnableDotInput(true);
